services:
  - type: web
    name: minecraft-inventory-backend
    env: docker
    plan: free
    repo: https://github.com/OmarKhamisBarakat/OmarKhamisBarakat.github.io
    rootDir: minecraft
    dockerContext: .
